from modules.add_command import AddCommand
from modules.remove_command import RemoveCommand
from modules.get_command import GetCommand
from modules.joke import Joke
from modules.lennyface import Lennyface
from modules.math import Math
from modules.eightball import EightBall
from modules.serverroles import ServerRoles
from modules.choose import Choose
from modules.dice import Dice
from modules.online import BotStart
from modules.roulette import Roulette
from modules.stab import Stab
from modules.slap import Slap
from modules.bank import Bank
from modules.points import UserPoints
from modules.ping import Ping
from modules.trump import Trump
from modules.catfact import CatFact
from modules.dogfact import DogFact
from modules.yomama import YoMama
from modules.chucknorris import ChuckNorris
from modules.dad import Dad
from modules.gender import Gender
from modules.geolocation import GeoLocation
from modules.weather import Weather
from modules.wikipedia import Wikipedia
from modules.youtube import Youtube
from modules.bitcoin import Bitcoin
from modules.roll import Roll
from modules.serverstats import ServerStats
from modules.reverse import Reverse
from modules.spongebob import SpOnGeBoB
from modules.slotmachine import SlotMachine
from modules.tokens import Tokens
from modules.urban import Urban
from modules.translate import Translate
from modules.aoruoka import AoRuoka
from modules.avatar import Avatar
from modules.catpicture import CatPicture
from modules.dogpicture import DogPicture
from modules.daily import Daily
from modules.duel import Duel
from modules.numberfact import NumberFact
from modules.pun import Pun
from modules.joinedtoserver import JoinedToServer
from modules.ip import ResolveIp
from modules.timer import Timer
from modules.rps import Rps
from modules.gettime import GetTime
from modules.guess import Guess
from modules.xp import GetXp
from modules.help import Help
from modules.google import Google
from modules.osu import Osu
from modules.transfer import Transfer
from modules.strawpoll import StrawPoll
from modules.playing import Playing
from modules.fishing import Fishing
from modules.gamble import Gamble
from modules.setavatar import SetAvatar
from modules.doubles import Doubles
from modules.nicknames import UserNickNames
from modules.purge import Purge
