from modules.add_command import AddCommand
from modules.remove_command import RemoveCommand
from modules.get_command import GetCommand
from modules.joke import Joke
from modules.lennyface import Lennyface
from modules.math import Math
from modules.eightball import EightBall
from modules.channels import ServerChannel
from modules.choose import Choose
from modules.dice import Dice
from modules.online import BotStart
from modules.roulette import Roulette
from modules.stab import Stab
from modules.slap import Slap
from modules.bank import Bank
from modules.points import UserPoints
from modules.ping import Ping
from modules.trump import Trump
from modules.catfact import CatFact
from modules.dogfact import DogFact
from modules.yomama import YoMama
from modules.chucknorris import ChuckNorris
from modules.dad import Dad
from modules.gender import Gender
from modules.geolocation import GeoLocation
from modules.weather import Weather
from modules.wikipedia import Wikipedia
from modules.youtube import Youtube
from modules.bitcoin import Bitcoin
from modules.roll import Roll
from modules.serverstats import ServerStats
from modules.reverse import Reverse
from modules.spongebob import SpOnGeBoB
from modules.slotmachine import SlotMachine
from modules.tokens import Tokens
from modules.urban import Urban
from modules.translate import Translate
