from modules.add_command import AddCommand
from modules.remove_command import RemoveCommand
from modules.get_command import GetCommand
from modules.joke import Joke
from modules.lennyface import Lennyface
from modules.math import Math
from modules.eightball import EightBall
from modules.channels import ServerChannel
from modules.choose import Choose
from modules.dice import Dice
from modules.online import BotStart
from modules.roulette import Roulette
from modules.stab import Stab
from modules.slap import Slap
